#!/bin/bash

ITERATIONS=5

cd "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd ..

args=""
echo "args: $args"

rm -f err
accuracies=()
for i in $(seq $ITERATIONS); do
  printf "\rIteration: $i / $ITERATIONS"
  output=$(./run $args 2>> err)
  accuracies+=($(echo "$output" | grep "Testing accuracy" | awk '{ print $3 }'))
done
echo

accuracies_sum=$(IFS="+"; bc <<< "${accuracies[*]}")
accuracies_len=${#accuracies[@]}

echo -n "Average accuracy: "
echo $(bc <<< "scale=2; $accuracies_sum / $accuracies_len")
