#!/usr/bin/env Rscript

library(tidyverse)
library(reshape2)
library(dplyr)
library(grid)
library(gridExtra)

results <- read.csv('results.csv', stringsAsFactors = FALSE)
rownames(results) <- results[, 1]
results <- results[, -1]
results$Secretion.high <- factor(results$Secretion.high)
results$Cytokines <- factor(results$Cytokines)

cells <- paste(results$Cells, 'cells')
cells_levels <- paste(unique(sort(results$Cells)), 'cells')
results$Cells <- factor(cells, levels = cells_levels)

results %>% ggplot(aes(x=Cell.types, y=Accuracy, color=Cytokines)) +
  stat_summary(geom = "line", fun = mean) +
  theme_bw() +
  theme(axis.title.y = element_text(angle = 0)) +
  facet_wrap(~Memory)
ggsave('plot.png', width = 20, height = 15)
