#!/usr/bin/env python3

import sys
import csv

assert len(sys.argv) == 4
idx = 0
with open(sys.argv[1]) as results1, open(sys.argv[2]) as results2, open(sys.argv[3], 'w') as results3:
  results1_reader = csv.reader(results1)
  results2_reader = csv.reader(results2)
  results3_writer = csv.writer(results3)
  for i, row in enumerate(results1_reader):
    if i == 0:
      results3_writer.writerow(row + [ 'ESM Communication' ])
    else:
      row[0] = idx
      results3_writer.writerow(row + [ 'No' ])
      idx += 1

  for i, row in enumerate(results2_reader):
    if i == 0:
      pass
    else:
      row[0] = idx
      results3_writer.writerow(row + [ 'Yes' ])
      idx += 1
