#!/bin/bash

cp -f results-proof-of-concept-combined.csv results.csv
./plot-combined System blue grey50
cp -f plot.png plot-proof-of-concept-combined.png

cp -f results-sensitivity-analysis.csv results.csv
./sensitivity-analysis

cp -f results-genes.csv results.csv
./plot-single-param Genes showacc "A)"
cp -f plot.png plot-genes.png

cp -f results-cells.csv results.csv
./plot-single-param Cells hideacc "B)"
convert plot.png -crop 1400x1500+100+0 +repage plot2.png
mv -f plot2.png plot-cells.png

cp -f results-strains.csv results.csv
./plot-single-param Strains hideacc "C)"
convert plot.png -crop 1400x1500+100+0 +repage plot2.png
mv -f plot2.png plot-strains.png

cp -f results-esms.csv results.csv
./plot-single-param ESMs hideacc "D)"
convert plot.png -crop 1400x1500+100+0 +repage plot2.png
mv -f plot2.png plot-esms.png

montage -mode concatenate -tile 4x1 -geometry -6+2 plot-genes.png plot-cells.png plot-strains.png plot-esms.png -resize 75% plot-3layers.png
