#!/usr/bin/env Rscript

library(tidyverse)
library(reshape2)
library(dplyr)
library(grid)
library(gridExtra)
library(stringi)

results <- read.csv('results.csv')
window_levels <- nlevels(factor(results$Window.size))

results$Function.text <- paste(stri_trans_totitle(results$Function), "function", sep = " ")
results$Window.size.text <- paste("Window size", results$Window.size, sep = " ")

results %>% ggplot(aes(x = Accuracy, fill = ESM.Communication)) +
  geom_histogram(binwidth = 0.025, alpha=0.5, position="identity") +
  scale_fill_manual(values=c("black", "blue")) +
  theme_bw() +
  theme(text = element_text(size = 14), panel.spacing.x = unit(4, "mm"), panel.spacing.y = unit(4, "mm")) +
  ylab("Experiments") +
  facet_grid(Function.text ~ results$Window.size.text) #, ncol=window_levels)
ggsave('plot.png', width = 10.0, height = 5.625)
