#!/usr/bin/env Rscript

library(tidyverse)
library(reshape2)
library(dplyr)
library(grid)
library(gridExtra)
library(stringr)

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1) {
  cat("Missing param to plot.")
  q()
}

results <- read.csv('results.csv')

ggplot(results, aes_string(x=args[1])) +
  geom_histogram() +
  theme_bw() +
  theme(text = element_text(size = 26), axis.title.y = element_text(angle = 0))
ggsave('plot.png', width = 10, height = 7.5)
