#!/usr/bin/env Rscript

library(tidyverse)
library(reshape2)
library(dplyr)
library(grid)
library(gridExtra)

results <- read.csv('results.csv')
rownames(results) <- results[, 1]
results <- results[, -1]
colnames(results)[2] <- 'Cell types'
colnames(results)[7] <- 'Cell grid spacing'
results$Secretion <- factor(results$Secretion)
results$Cells <- paste(results$Cells, 'cells')

mean_cl_quantile <- function(x, q = c(0.45, 0.55), na.rm = TRUE){
  dat <- data.frame(y = mean(x, na.rm = na.rm),
                    ymin = quantile(x, probs = q[1], na.rm = na.rm),
                    ymax = quantile(x, probs = q[2], na.rm = na.rm))
  return(dat)
}

# results %>% ggplot(aes(x=Threshold, y=Accuracy, color=Secretion)) +
#   stat_summary(geom = "line", fun = mean, size = 0.7) +
#   theme_bw() +
#   theme(axis.title.y = element_text(angle = 0)) +
#   facet_wrap(~`Cell grid spacing` + Lambda) +
#   ggtitle('Cells = 216, Cell types = 10, Cytokines = 3, Beta = 5, L = 1, K = 2, Output cells = 0.5, Output (internal) genes = 0.5,\nFunction = parity, Window = 5')
# ggsave('plot.png', width = 11, height = 7)

results %>% ggplot(aes(x=`Cell types`, y=Accuracy, color=Cytokines)) +
  stat_summary(geom = "line", fun = mean, size = 0.7) +
  theme_bw() +
  theme(axis.title.y = element_text(angle = 0)) +
  facet_wrap(~Cells) +
  ggtitle('Lambda = 3, Beta = 5, Threshold = 2, Secretion = 50, Cell grid spacing = 2, L = 1, K = 2, Output cells = 0.5,\nOutput (internal) genes = 0.5, Function = parity, Window = 5')
ggsave('plot.png', width = 11, height = 7)
