#!/usr/bin/env Rscript

library(tidyverse)
library(reshape2)
library(dplyr)
library(grid)
library(gridExtra)

results <- read.csv('results.csv')

results %>% ggplot(aes(x=Threshold, y=Accuracy)) +
  geom_line(aes(color=`Cell grid spacing`, shape=Secretion)) +
  theme_bw() +
  theme(axis.title.y = element_text(angle = 90)) +
  facet_wrap(~Lambda, scales = "free") +
