#!/bin/bash

# Lambda = sqrt(Beta / Alpha)
# Beta = 5
# Alpha = Beta / (Lambda ^ 2)

CELLS=( 200 )
CELL_TYPES=( 10 )
CYTOKINES=( 5 )
LAMBDAS=( 3 6 9 12 15 )
THRESHOLDS=(0.01 0.05 0.1 0.5 1.0 2.0)
WINDOWS=( 5 )
ITERATIONS=30

cd "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd ..

params_sets=()
iterations=()
for cells in ${CELLS[@]}; do
for cell_types in ${CELL_TYPES[@]}; do
for cytokines in ${CYTOKINES[@]}; do
for lambda in ${LAMBDAS[@]}; do
alpha=$(bc <<< "scale=2; 5 / ($lambda ^ 2)")
for threshold in ${THRESHOLDS[@]}; do
for window in ${WINDOWS[@]}; do
for iteration in $(seq $ITERATIONS); do
  params_sets+=("-c $cells -p $cell_types -y $cytokines -a $alpha -t $threshold -w $window")
  iterations+=($iteration)
done
done
done
done
done
done
done

function do_run() {
  echo "PARAMS: $1"
  outdir="output-"$(echo $1 | tr -d '-' | tr ' ' '_')"-#$2"
  ./run $1 -q $outdir
}
export -f do_run

results_dir=utils/results
rm -rf $results_dir
parallel -j 2 --results $results_dir --link do_run  ::: "${params_sets[@]}" ::: "${iterations[@]}" >/dev/null