#!/usr/bin/env python3

import seaborn as sns
import matplotlib.pyplot as plt
import sys
import numpy as np
import pandas as pd
import math
sns.set(font_scale=1.1)

data = { 'Window' : [], 'Lambda' : [], 'Cytokines' : [], 'Threshold' : [], 'Accuracy': [] }
with open(sys.argv[1], 'r') as f:
  
  for line in f:

    if line.startswith('PARAMS:'):
      tokens = line.split()

      window = int(tokens[3].split(',')[0])
      alpha = float(tokens[6].split(',')[0])
      lamb = round(math.sqrt(5 / alpha))
      cytokines = int(tokens[9].split(',')[0])
      threshold = float(tokens[12].split(',')[0])

      data['Window'].append(window)
      data['Lambda'].append(lamb)
      data['Cytokines'].append(str(cytokines) + " cytokines")
      data['Threshold'].append(threshold)

    if line.startswith('Testing accuracy:'):
      data['Accuracy'].append(float(line.split()[2]))

data = pd.DataFrame(data)

grid = sns.FacetGrid(data, col='Lambda', row='Window', hue='Cytokines')
grid = grid.map(sns.lineplot, 'Threshold', 'Accuracy')
grid.add_legend()
grid.axes[0, 0].set_ylabel('Accuracy', rotation=0, labelpad=37)
grid.axes[1, 0].set_ylabel('Accuracy', rotation=0, labelpad=37)
plt.subplots_adjust(left=0.125, top=0.7)
grid.fig.suptitle("Cells = 27, Cell types = 9, Genes = 5, In Degree = 2,\nFunction = parity, Beta = 5.0, Simulation steps = 100")
plt.savefig('fig.png')
