#!/bin/bash

N=( 10 20 30 40 50 100 200 300 400 500 )
L=( 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 0.10 )
K=( 1 2 3 )

ITERATIONS=30

cd "$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd ..
for n in ${N[@]}; do
  for k in ${K[@]}; do
    for i in $(seq $ITERATIONS); do
      echo "N = $n, K = $k, Iteration = $i"
      ./run -n $n -d $k -g
      sleep $(bc <<< "scale=1; $n / 50.")
    done
  done
done